<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE relacion[
<!ELEMENT relacion (persona)+>
<!ELEMENT persona (nombre,email*,parentesco?)>
<!ATTLIST persona carnet ID #REQUIRED>
<!ATTLIST persona sexo (hombre|mujer) #IMPLIED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT parentesco EMPTY>
<!ATTLIST parentesco tutor-legal IDREFS #IMPLIED hermano-a IDREFS #IMPLIED>
]>

<relacion>
  <persona carnet="si" sexo="hombre">
    <nombre>Antonio Hernandez</nombre>
    <email></email>
    <parentesco tutor-legal="Anastasia" hermano-a="Anastasia"></parentesco>
  </persona>
</relacion>