<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE note[
<!ELEMENT note (to+,from,heading*,(body|mensaje))>
<!ELEMENT to (#PCDATA)>
<!ELEMENT from (#PCDATA)>
<!ELEMENT heading (#PCDATA)>
<!ELEMENT body (#PCDATA)>
<!ELEMENT mensaje (#PCDATA)>
]>

<note>
    <to>Mercedes</to>
    <from>Jose</from>
    <heading>Recordar</heading>
    <mensaje>No olvides el cumpleaños de Andrés!</mensaje>
</note>